matrix:
  include:
    - language: clojure
      before_install:
        - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protoc-3.9.0-linux-x86_64.zip -o /tmp/protoc.zip
        - unzip /tmp/protoc.zip -d $HOME/protoc
        - export PATH=$HOME/protoc/bin:$PATH
        - sh scripts/distribute_proto.sh
        - cd product-service
      lein: lein
      script: lein protoc && lein test
      branches:
        only:
          - master
      jdk:
        - openjdk8
        - openjdk9
        - openjdk10
        - openjdk11
        - openjdk12

    - language: go
      before_install:
        - git clone --depth=50 --branch=master https://github.com/RenanPalmeira/hashlab-challenge.git hashlab-challenge
        - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.0/protoc-3.9.0-linux-x86_64.zip -o /tmp/protoc.zip
        - unzip /tmp/protoc.zip -d $HOME/protoc
        - export PATH=$HOME/protoc/bin:$PATH
        - sh scripts/distribute_proto.sh
        - go get google.golang.org/grpc
        - go get github.com/golang/protobuf/protoc-gen-go
        - go get go.mongodb.org/mongo-driver/mongo
        - go get github.com/crgimenes/goconfig
      script:
        - go test -v -race ./...
      env:
        - GO111MODULE=off
      git:
        depth: false
      branches:
        only:
          - master
      go:
        - 1.12.x
