version: '3'
services:

  product-service:
    build: product-service/
    ports:
      - "8080:8080"
    links:
      - hashlab-postgres
      - discount-service
    environment:
      - HASHLAB_DISCOUNT_SERVICE_URI=discount-service:50051
      - HASHLAB_POSTGRES_CONNECTION_URI=jdbc:postgresql://hashlab-postgres:5432/hashlab?user=hashlab&password=hashlab
      - HASHLAB_PRODUCTION_SERVICE_PER_PAGE=20

  discount-service:
    build: discount-service
    links:
      - user-service
    ports:
      - "50051:50051"
    environment:
      - HASHLAB_USER_SERVICE_URI=user-service:50052
      - HASHLAB_DISCOUNT_SERVICE_PORT=:50051

  user-service:
    build: user-service
    links:
      - hashlab-mongodb
    ports:
      - "50052:50052"
    environment:
      - HASHLAB_USER_SERVICE_PORT=:50052
      - HASHLAB_MONGODB_HOST=hashlab-mongodb
      - HASHLAB_MONGODB_USERNAME=hashlab
      - HASHLAB_MONGODB_PASSWORD=hashlab
      - HASHLAB_MONGODB_DATABASE=admin

  hashlab-mongodb:
    image: mongo:4.0.11
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hashlab
      - MONGO_INITDB_ROOT_PASSWORD=hashlab

  hashlab-postgres:
    image: postgres:9.6.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hashlab
      - POSTGRES_PASSWORD=hashlab

  hashlab-postgres-phppgadmin:
    image: dockage/phppgadmin:latest
    links:
      - hashlab-postgres
    ports:
      - "9000:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST=hashlab-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432