version: '3'
services:

  product-service:
    build: product-service/Dockerfile
    ports:
      - "8080:8080"
    links:
      - hashlab-postgres

  discount-service:
    build: discount-service/Dockerfile
    ports:
      - "8080:8080"
    links:
      - hashlab-mongodb

  user-service:
    build: product-service/Dockerfile
    ports:
      - "8080:8080"
    links:
      - hashlab-postgres

  hashlab-mongodb:
    image: mongo:4.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: hashlab
      MONGO_INITDB_ROOT_PASSWORD: hashlab
    ports:
      - "27017:27017"

  hashlab-postgres:
    image: postgres:9.6.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hashlab
      - POSTGRES_PASSWORD=hashlab

  hashlab-postgres-phppgadmin:
    image: dockage/phppgadmin:latest
    links:
      - hashlab-postgres
    ports:
      - "9000:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432